apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels: 
    {{ include "website.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    {{ include "website.selectorLabels" . | nindent 4 }}
